### ISSUE TITLE
Error when running grunt watch

### ISSUE THREAD

**Issue by njpatten** [10up/generator-wp-make#68] opened 2016-05-04 19:56 UTC
With the new version when I run 'yo wp-make:theme' then 'grunt watch' I get an infinite loop with the following error:

```
Running "watch" task 
Waiting...
Verifying property watch exists in config...ERROR
>> Unable to process task.
Warning: Required config property "watch" missing.
```

I haven't made any changes to any of the grunt files so I'm not sure why this is happening. Didn't happen with the previous version. Please let me know if this is a bug.

**Comment by allenmoore** [comment] 2016-05-05 14:29
Hey @njpatten,

I just tested the watch task with the latest version of generator and I was not able to reproduce this error. Can you check which version of generator you have installed? Run the following command in terminal and verify that the version is 0.4.1:

```
npm list -g generator-wp-make
```

If you are using an older version of the generator, try updating to the latest version. Can you also post the contents of the watch task?

Thank you,
Allen Moore

**Comment by njpatten** [comment] 2016-06-13 19:58
Hi @allenmoore,

It looks like the problem is the extra errant bracket that was fixed [here](https://github.com/10up/generator-wp-make/commit/034989d7feb65aad7037fbbc0b28d87f62e38d1b)

I've updated yeoman but I am still having the problem and I need to manually remove all of the errant brackets for it to work. Any suggestions on fixing this problem permanently?

Thanks,
Nicole

**Comment by allenmoore** [comment] 2016-06-29 13:41
Hey @njpatten,

If you are experiencing this issue after the update then it may be a good idea to reinstall the generator. Here are the steps to reinstall the generator from terminal:
1. Run `npm uninstall generator-wp-make -g'
2. Navigate to the local directory where the generator repo was closed with git using`cd path/to/directory`
3. Run`git branch`and verify that you are on the master branch. Then run`git fetch`followed by`git pull origin master`.
4. Run`npm link` which will link the generator to node/yeoman.

After you have completed these steps, please test generating a new plugin/theme, and reply with a comment with the results.

Thank you,
Allen Moore

**Comment by njpatten** [comment] 2016-07-12 17:26
Yes, that worked. Thank you very much!

**Comment by allenmoore** [comment] 2016-07-19 01:51
Hey @njpatten,

That's great to hear. I'm going to close this issue and consider it resolved.

Thank you,
Allen Moore

**Closed as completed by allenmoore** 2016-07-19 01:51 UTC
